name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  config: Release
  disable_test_parallelization: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  pg_db: marten_testing
  pg_user: postgres

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20


    steps:
    - uses: actions/checkout@v2

    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test src/Alba.Testing/Alba.Testing.csproj
